spring.application.name=bottega-web

# Connessione al Cloud Aiven
spring.datasource.url=jdbc:mysql://mysql-210fd27f-mattyorlando17-8549.i.aivencloud.com:16692/defaultdb?useSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=LA_AVNS_AvMNN9L9TpDcP0GModV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# MAGIA DI HIBERNATE (JPA) - CREAZIONE TABELLE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Altre configurazioni
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
